apiVersion: v1
data:
  password: {{ .Values.portDbUser | b64enc }}
  username: {{ .Values.portDbpass | b64enc }}
kind: Secret
metadata:
  labels:
    EntandoApp: {{ .Values.appName }}
  name: {{ .Values.appName }}-portdb-secret
  namespace: {{ .Values.nameSpace }}
type: Opaque
---
apiVersion: v1
data:
  password: {{ .Values.servDbUser | b64enc }}
  username: {{ .Values.servDbPass | b64enc }}
kind: Secret
metadata:
  labels:
    EntandoApp: {{ .Values.appName }}
  name: {{ .Values.appName }}-servdb-secret
  namespace: {{ .Values.nameSpace }}
type: Opaque
---
apiVersion: v1
data:
  clientId: {{ .Values.kcClientId | b64enc }}
  clientSecret: {{ .Values.kcClientSecret | b64enc }}
kind: Secret
metadata:
  name: {{ .Values.appName }}-secret
  namespace: {{ .Values.nameSpace }}
type: Opaque